"""create memories table

Revision ID: f1f135c6cce8
Revises: f0d5e1e93e51
Create Date: 2026-06-30 02:41:17.750087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f135c6cce8'
down_revision: Union[str, Sequence[str], None] = 'f0d5e1e93e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('content', sa.Text(), nullable=False))
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.drop_column('memories', 'key')
    op.drop_column('memories', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_column('memories', 'content')
    # ### end Alembic commands ###
